spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: kiot
    password: zpdliot1!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  thymeleaf:
    cache: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: kakao client ID
            client-secret: kakao client KEY
          naver:
            client-id: naver client ID
            client-secret: naver client KEY

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

